bind '"\er": redraw-current-line'
bind '"\C-g\C-f": "$(fzf-git gf)\e\C-e\er"'
bind '"\C-g\C-b": "$(fzf-git gb)\e\C-e\er"'
bind '"\C-g\C-t": "$(fzf-git gt)\e\C-e\er"'
bind '"\C-g\C-h": "$(fzf-git gh)\e\C-e\er"'
bind '"\C-gh":    "$(fzf-git gh)\e\C-e\er"'
bind '"\C-g\C-r": "$(fzf-git gr)\e\C-e\er"'
